// Package opi_nvidia provides the control-plane translation engine mapping
// vendor-neutral OPI abstractions to the southbound NVIDIA DPF API surface.
package opi_nvidia

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// Finalizer and requeue intervals.
const (
	OPIFinalizer           = "opi.dpu.io/dpf-adapter-finalizer"
	DefaultRequeueInterval = 30 * time.Second
	// HardwareRequeueInterval gives physical DPUs time to complete a PCIe cold-boot.
	HardwareRequeueInterval = 60 * time.Second
	DPFNamespace            = "dpf-operator-system"
)

// OPIDPUSet phase values for the provisioning state machine.
const (
	PhaseBootImageMapping      = "BootImageMapping"
	PhaseClusterIsolation      = "ClusterIsolation"
	PhaseRollingRollout        = "RollingRollout"
	PhaseAwaitingHardwareReset = "AwaitingHardwareReset"
	PhaseReady                 = "Ready"
	PhaseError                 = "Error"
)

// OPI-side CRD types. In a real project these come from api/v1alpha1/ and
// have DeepCopy generated by controller-gen.

// OPIDPUSet is the vendor-neutral DPU provisioning resource.
type OPIDPUSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OPIDPUSetSpec   `json:"spec,omitempty"`
	Status            OPIDPUSetStatus `json:"status,omitempty"`
}

type OPIDPUSetSpec struct {
	Vendor        string            `json:"vendor"`
	Count         int32             `json:"count"`
	NodeSelector  map[string]string `json:"nodeSelector,omitempty"`
	FirmwareImage FirmwareImageRef  `json:"firmwareImage"`
	DPUProfile    string            `json:"dpuProfile,omitempty"`
	// VendorExtensions holds raw, provider-specific configuration payloads passed
	// directly to the southbound driver adapter.
	// +optional
	// +kubebuilder:validation:XPreserveUnknownFields
	VendorExtensions *runtime.RawExtension `json:"vendorExtensions,omitempty"`
}

type FirmwareImageRef struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	URL     string `json:"url,omitempty"`
}

// NvidiaVendorExtensions is the NVIDIA adapter's private deserialization
// target for VendorExtensions. Not part of the OPI CRD schema.
type NvidiaVendorExtensions struct {
	BFBURL     string            `json:"bfbURL,omitempty"`
	DPUCluster *DPUClusterConfig `json:"dpuCluster,omitempty"`
}

type DPUClusterConfig struct {
	Enabled bool   `json:"enabled"`
	Type    string `json:"type,omitempty"` // "static" or "dynamic"
}

type OPIDPUSetStatus struct {
	// Phase is one of: BootImageMapping, ClusterIsolation, RollingRollout,
	// AwaitingHardwareReset, Ready, Degraded, Error.
	Phase        string              `json:"phase,omitempty"`
	DPUCount     int32               `json:"dpuCount,omitempty"`
	ReadyCount   int32               `json:"readyCount,omitempty"`
	Conditions   []metav1.Condition  `json:"conditions,omitempty"`
	VendorStatus *NvidiaVendorStatus `json:"vendorStatus,omitempty"`
}

// OPIDPUSetList contains a list of OPIDPUSet
type OPIDPUSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OPIDPUSet `json:"items"`
}

// DeepCopyObject is a stub to satisfy the runtime.Object interface.
// In a real project, this is auto-generated by controller-gen.
func (in *OPIDPUSet) DeepCopyObject() runtime.Object     { return in }
func (in *OPIDPUSetList) DeepCopyObject() runtime.Object { return in }

// NvidiaVendorStatus captures DPF-specific status details.
type NvidiaVendorStatus struct {
	DPFDPUSetName  string `json:"dpfDPUSetName,omitempty"`
	DPFDPUSetPhase string `json:"dpfDPUSetPhase,omitempty"`
}

// OPIDPUService represents a service to deploy onto DPUs via OPI.
type OPIDPUService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OPIDPUServiceSpec   `json:"spec,omitempty"`
	Status            OPIDPUServiceStatus `json:"status,omitempty"`
}

// OPIDPUServiceList contains a list of OPIDPUService
type OPIDPUServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OPIDPUService `json:"items"`
}

// DeepCopyObject is a stub to satisfy the runtime.Object interface.
func (in *OPIDPUService) DeepCopyObject() runtime.Object     { return in }
func (in *OPIDPUServiceList) DeepCopyObject() runtime.Object { return in }

func (in *BFB) DeepCopyObject() runtime.Object { return in }
func (in *DPUSet) DeepCopyObject() runtime.Object { return in }
func (in *DPUCluster) DeepCopyObject() runtime.Object { return in }
func (in *DPUService) DeepCopyObject() runtime.Object { return in }


// OPIDPUServiceSpec defines the desired state of an OPIDPUService.
type OPIDPUServiceSpec struct {
	Vendor        string        `json:"vendor"`
	ServiceType   string        `json:"serviceType"` // networking, storage, security, custom
	TargetDPUSet  string        `json:"targetDPUSet"`
	Configuration HelmChartSpec `json:"configuration"`
}

// HelmChartSpec describes a Helm chart to deploy.
type HelmChartSpec struct {
	Repository string            `json:"repository"`
	Name       string            `json:"name"`
	Version    string            `json:"version"`
	Values     map[string]string `json:"values,omitempty"`
}

// OPIDPUServiceStatus defines the observed state of an OPIDPUService.
type OPIDPUServiceStatus struct {
	Phase        string                 `json:"phase,omitempty"` // Pending, Deploying, Deployed, Degraded, Error
	Conditions   []metav1.Condition     `json:"conditions,omitempty"`
	VendorStatus *NvidiaSvcVendorStatus `json:"vendorStatus,omitempty"`
}

// NvidiaSvcVendorStatus captures DPF DPUService-specific status details.
type NvidiaSvcVendorStatus struct {
	DPFDPUServiceName  string `json:"dpfDPUServiceName,omitempty"`
	DPFDPUServicePhase string `json:"dpfDPUServicePhase,omitempty"`
}

// DPF-side stub types. Replace with imports from github.com/NVIDIA/doca-platform/api/.

// BFB represents a NVIDIA BlueField Boot Bundle (DPF CRD).
type BFB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BFBSpec   `json:"spec,omitempty"`
	Status            BFBStatus `json:"status,omitempty"`
}

type BFBSpec struct {
	URL     string `json:"url"`
	Version string `json:"version,omitempty"`
}

type BFBStatus struct {
	Phase string `json:"phase,omitempty"` // Ready, Error
}

// DPUSet represents a NVIDIA DPF DPUSet (DPF CRD).
type DPUSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DPUSetSpec   `json:"spec,omitempty"`
	Status            DPUSetStatus `json:"status,omitempty"`
}

type DPUSetSpec struct {
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	BFBRef       string            `json:"bfbRef"`
	Count        int32             `json:"count,omitempty"`
}

type DPUSetStatus struct {
	Phase      string `json:"phase,omitempty"` // Provisioning, Ready, Error
	ReadyCount int32  `json:"readyCount,omitempty"`
	TotalCount int32  `json:"totalCount,omitempty"`
}

// DPUCluster represents a NVIDIA DPF DPUCluster (DPF CRD).
type DPUCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DPUClusterSpec `json:"spec,omitempty"`
}

type DPUClusterSpec struct {
	Type string `json:"type,omitempty"`
}

// DPUService represents a NVIDIA DPF DPUService (DPF CRD).
type DPUService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DPUServiceSpec   `json:"spec,omitempty"`
	Status            DPUServiceStatus `json:"status,omitempty"`
}

type DPUServiceSpec struct {
	HelmChart HelmChartRef `json:"helmChart"`
}

type HelmChartRef struct {
	Repository string            `json:"repository"`
	Name       string            `json:"name"`
	Version    string            `json:"version"`
	Values     map[string]string `json:"values,omitempty"`
}

type DPUServiceStatus struct {
	Phase string `json:"phase,omitempty"` // Deploying, Ready, Error
}

// DPFAdapter is the southbound interface for the NVIDIA adapter.
// Keeping it behind an interface lets tests inject a mock without a live cluster.
type DPFAdapter interface {
	// EnsureBFB creates or updates a DPF BFB resource from an OPIDPUSet.
	EnsureBFB(ctx context.Context, opiDPUSet *OPIDPUSet) (*BFB, error)

	// EnsureDPUSet creates or updates a DPF DPUSet from an OPIDPUSet.
	EnsureDPUSet(ctx context.Context, opiDPUSet *OPIDPUSet, bfb *BFB) (*DPUSet, error)

	// EnsureDPUCluster optionally creates a DPF DPUCluster from an OPIDPUSet.
	EnsureDPUCluster(ctx context.Context, opiDPUSet *OPIDPUSet) (*DPUCluster, error)

	// EnsureDPUService creates or updates a DPF DPUService from an OPIDPUService.
	EnsureDPUService(ctx context.Context, opiSvc *OPIDPUService) (*DPUService, error)

	// GetDPUSetStatus retrieves the current status of a DPF DPUSet.
	GetDPUSetStatus(ctx context.Context, name, namespace string) (*DPUSetStatus, error)

	// GetDPUServiceStatus retrieves the current status of a DPF DPUService.
	GetDPUServiceStatus(ctx context.Context, name, namespace string) (*DPUServiceStatus, error)

	// DeleteDPFResources cleans up all DPF resources owned by the given OPI resource.
	DeleteDPFResources(ctx context.Context, owner client.Object) error
}

// StatusMapper translates DPF phase strings into OPI status conditions.
type StatusMapper struct{}

// MapDPUSetPhase converts a DPF DPUSet phase string into an OPI phase and conditions.
func (m *StatusMapper) MapDPUSetPhase(dpfStatus DPUSetStatus) (string, []metav1.Condition) {
	now := metav1.Now()
	var opiPhase string
	var conditions []metav1.Condition

	switch dpfStatus.Phase {
	case "Ready":
		opiPhase = "Ready"
		conditions = append(conditions, metav1.Condition{
			Type:               "DPUsReady",
			Status:             metav1.ConditionTrue,
			LastTransitionTime: now,
			Reason:             "AllDPUsProvisioned",
			Message:            fmt.Sprintf("%d of %d DPUs ready", dpfStatus.ReadyCount, dpfStatus.TotalCount),
		})
	case "Provisioning":
		opiPhase = "Provisioning"
		conditions = append(conditions, metav1.Condition{
			Type:               "DPUsReady",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: now,
			Reason:             "ProvisioningInProgress",
			Message:            fmt.Sprintf("%d of %d DPUs ready", dpfStatus.ReadyCount, dpfStatus.TotalCount),
		})
	case "Error":
		opiPhase = "Error"
		conditions = append(conditions, metav1.Condition{
			Type:               "DPUsReady",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: now,
			Reason:             "DPFError",
			Message:            "DPF DPUSet reported an error",
		})
	default:
		opiPhase = "Unknown"
		conditions = append(conditions, metav1.Condition{
			Type:               "DPUsReady",
			Status:             metav1.ConditionUnknown,
			LastTransitionTime: now,
			Reason:             "UnknownDPFPhase",
			Message:            fmt.Sprintf("Unrecognized DPF phase: %s", dpfStatus.Phase),
		})
	}

	return opiPhase, conditions
}

// MapDPUServicePhase converts a DPF DPUService phase into an OPI phase and conditions.
func (m *StatusMapper) MapDPUServicePhase(dpfStatus DPUServiceStatus) (string, []metav1.Condition) {
	now := metav1.Now()
	var opiPhase string
	var conditions []metav1.Condition

	switch dpfStatus.Phase {
	case "Ready":
		opiPhase = "Deployed"
		conditions = append(conditions, metav1.Condition{
			Type:               "ServiceHealthy",
			Status:             metav1.ConditionTrue,
			LastTransitionTime: now,
			Reason:             "AllReplicasReady",
			Message:            "DPUService is healthy",
		})
	case "Deploying":
		opiPhase = "Deploying"
		conditions = append(conditions, metav1.Condition{
			Type:               "ServiceHealthy",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: now,
			Reason:             "DeploymentInProgress",
			Message:            "DPUService is being deployed",
		})
	case "Error":
		opiPhase = "Error"
		conditions = append(conditions, metav1.Condition{
			Type:               "ServiceHealthy",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: now,
			Reason:             "DPFServiceError",
			Message:            "DPF DPUService reported an error",
		})
	default:
		opiPhase = "Pending"
	}

	return opiPhase, conditions
}

// NvidiaDPFAdapter implements DPFAdapter using a controller-runtime client
// to manage DPF CRDs in the same Kubernetes cluster.
type NvidiaDPFAdapter struct {
	Client       client.Client
	Scheme       *runtime.Scheme
	DPFNamespace string
}

// NewNvidiaDPFAdapter creates a new adapter with defaults.
func NewNvidiaDPFAdapter(c client.Client, scheme *runtime.Scheme) *NvidiaDPFAdapter {
	return &NvidiaDPFAdapter{
		Client:       c,
		Scheme:       scheme,
		DPFNamespace: DPFNamespace,
	}
}

func (a *NvidiaDPFAdapter) dpfName(opiName string) string {
	return opiName + "-dpf"
}

// parseVendorExtensions deserializes the opaque VendorExtensions blob into
// a NvidiaVendorExtensions struct. Returns nil if no extensions are present.
func (a *NvidiaDPFAdapter) parseVendorExtensions(opiDPUSet *OPIDPUSet) (*NvidiaVendorExtensions, error) {
	if opiDPUSet.Spec.VendorExtensions == nil || opiDPUSet.Spec.VendorExtensions.Raw == nil {
		return nil, nil
	}
	ext := &NvidiaVendorExtensions{}
	if err := json.Unmarshal(opiDPUSet.Spec.VendorExtensions.Raw, ext); err != nil {
		return nil, fmt.Errorf("failed to deserialize NVIDIA vendor extensions: %w", err)
	}
	return ext, nil
}

// EnsureBFB creates or updates a BFB resource from an OPIDPUSet spec.
func (a *NvidiaDPFAdapter) EnsureBFB(ctx context.Context, opiDPUSet *OPIDPUSet) (*BFB, error) {
	logger := log.FromContext(ctx)

	bfb := &BFB{
		ObjectMeta: metav1.ObjectMeta{
			Name:      a.dpfName(opiDPUSet.Name) + "-bfb",
			Namespace: a.DPFNamespace,
		},
	}

	// Determine BFB URL: prefer vendor extension override, fall back to firmware spec.
	bfbURL := opiDPUSet.Spec.FirmwareImage.URL
	ext, err := a.parseVendorExtensions(opiDPUSet)
	if err != nil {
		return nil, err
	}
	if ext != nil && ext.BFBURL != "" {
		bfbURL = ext.BFBURL
	}

	op, err := controllerutil.CreateOrUpdate(ctx, a.Client, bfb, func() error {
		if err := controllerutil.SetControllerReference(opiDPUSet, bfb, a.Scheme); err != nil {
			return err
		}
		bfb.Spec.URL = bfbURL
		bfb.Spec.Version = opiDPUSet.Spec.FirmwareImage.Version
		return nil
	})
	if err != nil {
		return nil, err
	}
	logger.Info("EnsureBFB completed", "name", bfb.Name, "operation", op)
	return bfb, nil
}

// EnsureDPUSet creates or updates a DPUSet resource from an OPIDPUSet spec.
func (a *NvidiaDPFAdapter) EnsureDPUSet(ctx context.Context, opiDPUSet *OPIDPUSet, bfb *BFB) (*DPUSet, error) {
	logger := log.FromContext(ctx)

	dpuSet := &DPUSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      a.dpfName(opiDPUSet.Name),
			Namespace: a.DPFNamespace,
		},
	}

	op, err := controllerutil.CreateOrUpdate(ctx, a.Client, dpuSet, func() error {
		if err := controllerutil.SetControllerReference(opiDPUSet, dpuSet, a.Scheme); err != nil {
			return err
		}
		dpuSet.Spec.NodeSelector = opiDPUSet.Spec.NodeSelector
		dpuSet.Spec.BFBRef = bfb.Name
		dpuSet.Spec.Count = opiDPUSet.Spec.Count
		return nil
	})
	if err != nil {
		return nil, err
	}
	logger.Info("EnsureDPUSet completed", "name", dpuSet.Name, "operation", op)
	return dpuSet, nil
}

// EnsureDPUCluster optionally creates a DPUCluster if configured in vendor extensions.
func (a *NvidiaDPFAdapter) EnsureDPUCluster(ctx context.Context, opiDPUSet *OPIDPUSet) (*DPUCluster, error) {
	logger := log.FromContext(ctx)

	// Deserialize opaque vendor extensions to extract DPUCluster config.
	ext, err := a.parseVendorExtensions(opiDPUSet)
	if err != nil {
		return nil, err
	}
	if ext == nil || ext.DPUCluster == nil || !ext.DPUCluster.Enabled {
		return nil, nil
	}

	dpuCluster := &DPUCluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:      a.dpfName(opiDPUSet.Name) + "-cluster",
			Namespace: a.DPFNamespace,
		},
	}

	op, err := controllerutil.CreateOrUpdate(ctx, a.Client, dpuCluster, func() error {
		if err := controllerutil.SetControllerReference(opiDPUSet, dpuCluster, a.Scheme); err != nil {
			return err
		}
		dpuCluster.Spec.Type = ext.DPUCluster.Type
		return nil
	})
	if err != nil {
		return nil, err
	}
	logger.Info("EnsureDPUCluster completed", "name", dpuCluster.Name, "operation", op)
	return dpuCluster, nil
}

// EnsureDPUService creates or updates a DPF DPUService from an OPIDPUService spec.
func (a *NvidiaDPFAdapter) EnsureDPUService(ctx context.Context, opiSvc *OPIDPUService) (*DPUService, error) {
	logger := log.FromContext(ctx)

	dpuService := &DPUService{
		ObjectMeta: metav1.ObjectMeta{
			Name:      a.dpfName(opiSvc.Name),
			Namespace: a.DPFNamespace,
		},
	}

	op, err := controllerutil.CreateOrUpdate(ctx, a.Client, dpuService, func() error {
		if err := controllerutil.SetControllerReference(opiSvc, dpuService, a.Scheme); err != nil {
			return err
		}
		dpuService.Spec.HelmChart = HelmChartRef{
			Repository: opiSvc.Spec.Configuration.Repository,
			Name:       opiSvc.Spec.Configuration.Name,
			Version:    opiSvc.Spec.Configuration.Version,
			Values:     opiSvc.Spec.Configuration.Values,
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	logger.Info("EnsureDPUService completed", "name", dpuService.Name, "operation", op)
	return dpuService, nil
}

// GetDPUSetStatus retrieves the current DPUSet status from the cluster.
func (a *NvidiaDPFAdapter) GetDPUSetStatus(ctx context.Context, name, namespace string) (*DPUSetStatus, error) {
	// Stub: in a real implementation, fetch the DPUSet and return its status.
	return &DPUSetStatus{
		Phase:      "Provisioning",
		ReadyCount: 0,
		TotalCount: 0,
	}, nil
}

// GetDPUServiceStatus retrieves the current DPUService status from the cluster.
func (a *NvidiaDPFAdapter) GetDPUServiceStatus(ctx context.Context, name, namespace string) (*DPUServiceStatus, error) {
	// Stub: in a real implementation, fetch the DPUService and return its status.
	return &DPUServiceStatus{
		Phase: "Deploying",
	}, nil
}

// DeleteDPFResources removes all DPF resources owned by the given OPI resource.
func (a *NvidiaDPFAdapter) DeleteDPFResources(ctx context.Context, owner client.Object) error {
	logger := log.FromContext(ctx)
	logger.Info("DeleteDPFResources stub: would delete all DPF resources owned by", "owner", owner.GetName())
	// In a real implementation: list DPF resources with owner reference matching,
	// or delete by known naming convention, then verify deletion.
	return nil
}

// OPIDPUSetReconciler reconciles OPIDPUSet objects by translating them into
// DPF CRDs via the DPFAdapter and mapping status back.
//
// NOTE: This reconciler is registered strictly for the NVIDIA provider. The
// main OPI operator owns higher-level routing and dispatches to vendor-specific
// reconcilers (like this one) based on the spec.vendor field.
type OPIDPUSetReconciler struct {
	client.Client
	Scheme       *runtime.Scheme
	Adapter      DPFAdapter
	StatusMapper *StatusMapper
}

// Reconcile implements the phase-gated state machine for OPIDPUSet resources.
// Each phase is a gate: the reconciler exits and requeues after each phase
// until the gate condition is met, preventing reconciliation thrashing during
// multi-gigabyte BFB downloads and physical RSHIM driver interactions.
func (r *OPIDPUSetReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	logger.Info("Reconciling OPIDPUSet", "name", req.NamespacedName)

	// 1. Fetch the OPIDPUSet resource.
	opiDPUSet := &OPIDPUSet{}
	if err := r.Get(ctx, req.NamespacedName, opiDPUSet); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	// 2. Vendor dispatch: only handle NVIDIA.
	if opiDPUSet.Spec.Vendor != "nvidia" {
		logger.Info("Skipping non-NVIDIA OPIDPUSet", "vendor", opiDPUSet.Spec.Vendor)
		return ctrl.Result{}, nil
	}

	// 3. Handle deletion with finalizer.
	if !opiDPUSet.DeletionTimestamp.IsZero() {
		if controllerutil.ContainsFinalizer(opiDPUSet, OPIFinalizer) {
			if err := r.Adapter.DeleteDPFResources(ctx, opiDPUSet); err != nil {
				logger.Error(err, "Failed to delete DPF resources")
				return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
			}
			controllerutil.RemoveFinalizer(opiDPUSet, OPIFinalizer)
			if err := r.Update(ctx, opiDPUSet); err != nil {
				return ctrl.Result{}, err
			}
		}
		return ctrl.Result{}, nil
	}

	// 4. Ensure finalizer is present.
	if !controllerutil.ContainsFinalizer(opiDPUSet, OPIFinalizer) {
		controllerutil.AddFinalizer(opiDPUSet, OPIFinalizer)
		if err := r.Update(ctx, opiDPUSet); err != nil {
			return ctrl.Result{}, err
		}
	}

	// ---------------------------------------------------------------
	// Phase-Gated State Machine
	// Each phase gate exits early with a requeue if the gate condition
	// is not met, preventing concurrent orchestration thrashing.
	// ---------------------------------------------------------------

	// Phase 1: BootImageMapping — Validate and assert BFB resource state.
	// Gate: BFB must report Ready before we proceed to DPUSet creation.
	bfb, err := r.Adapter.EnsureBFB(ctx, opiDPUSet)
	if err != nil {
		if isUnrecoverableError(err) {
			return r.setTerminalError(ctx, opiDPUSet, "BFBValidationFailed", err)
		}
		logger.Error(err, "Failed to ensure BFB")
		r.setErrorStatus(ctx, opiDPUSet, "BFBSyncFailed", err.Error())
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}

	// Check BFB gate: BFB must be Ready before proceeding.
	if bfb.Status.Phase != "Ready" {
		logger.Info("BFB not yet ready, holding at BootImageMapping gate", "bfbPhase", bfb.Status.Phase)
		opiDPUSet.Status.Phase = PhaseBootImageMapping
		opiDPUSet.Status.Conditions = []metav1.Condition{{
			Type:               "BFBReady",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: metav1.Now(),
			Reason:             "WaitingForBFBRegistration",
			Message:            fmt.Sprintf("BFB image metadata not yet registered (current: %s)", bfb.Status.Phase),
		}}
		_ = r.Status().Update(ctx, opiDPUSet)
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
	}

	// Phase 2: ClusterIsolation — Trigger DPUCluster orchestration.
	// Gate: DPUCluster must be Ready before DPUSet provisioning.
	dpuCluster, err := r.Adapter.EnsureDPUCluster(ctx, opiDPUSet)
	if err != nil {
		if isUnrecoverableError(err) {
			return r.setTerminalError(ctx, opiDPUSet, "DPUClusterValidationFailed", err)
		}
		logger.Error(err, "Failed to ensure DPUCluster")
		r.setErrorStatus(ctx, opiDPUSet, "DPUClusterSyncFailed", err.Error())
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}

	// If DPUCluster is required but not yet initialized, hold at gate.
	if dpuCluster != nil {
		// Stub: in real impl, check dpuCluster.Status.Phase
		// For now, assume cluster needs initialization.
		logger.Info("DPUCluster created, checking initialization", "name", dpuCluster.Name)
		opiDPUSet.Status.Phase = PhaseClusterIsolation
		// In production, we would check dpuCluster.Status.Phase == "Ready"
		// and requeue if not. For skeleton, we proceed.
	}

	// Phase 3: RollingRollout — Apply DPUSet to trigger physical flashing.
	dpuSet, err := r.Adapter.EnsureDPUSet(ctx, opiDPUSet, bfb)
	if err != nil {
		if isUnrecoverableError(err) {
			return r.setTerminalError(ctx, opiDPUSet, "DPUSetValidationFailed", err)
		}
		logger.Error(err, "Failed to ensure DPUSet")
		r.setErrorStatus(ctx, opiDPUSet, "DPUSetSyncFailed", err.Error())
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}
	_ = dpuSet // Used for owner reference in real impl

	// Sync status from DPF DPUSet back to OPI.
	dpfDPUSetName := opiDPUSet.Name + "-dpf"
	dpfStatus, err := r.Adapter.GetDPUSetStatus(ctx, dpfDPUSetName, DPFNamespace)
	if err != nil {
		logger.Error(err, "Failed to get DPUSet status from DPF")
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}

	opiPhase, conditions := r.StatusMapper.MapDPUSetPhase(*dpfStatus)

	// Handle hardware cold-boot / PCIe reset: exit gracefully WITHOUT error
	// to prevent controller-manager exponential-backoff thrashing on normal
	// hardware lifecycle events.
	if dpfStatus.Phase == "AwaitingReboot" {
		logger.Info("Hardware PCIe cold-boot required, parking at AwaitingHardwareReset")
		opiDPUSet.Status.Phase = PhaseAwaitingHardwareReset
		opiDPUSet.Status.ReadyCount = dpfStatus.ReadyCount
		opiDPUSet.Status.DPUCount = dpfStatus.TotalCount
		opiDPUSet.Status.Conditions = []metav1.Condition{{
			Type:               "HardwareResetRequired",
			Status:             metav1.ConditionTrue,
			LastTransitionTime: metav1.Now(),
			Reason:             "PCIeColdBootPending",
			Message:            "One or more DPUs require a physical PCIe cold-boot reset",
		}}
		_ = r.Status().Update(ctx, opiDPUSet)
		// Return nil error: this is a normal hardware lifecycle event.
		return ctrl.Result{RequeueAfter: HardwareRequeueInterval}, nil
	}

	// Map DPF phase to OPI phase.
	if opiPhase != PhaseReady {
		opiDPUSet.Status.Phase = PhaseRollingRollout
	} else {
		opiDPUSet.Status.Phase = PhaseReady
	}
	opiDPUSet.Status.ReadyCount = dpfStatus.ReadyCount
	opiDPUSet.Status.DPUCount = dpfStatus.TotalCount
	opiDPUSet.Status.Conditions = conditions
	opiDPUSet.Status.VendorStatus = &NvidiaVendorStatus{
		DPFDPUSetName:  dpfDPUSetName,
		DPFDPUSetPhase: dpfStatus.Phase,
	}

	// Add the synced condition.
	opiDPUSet.Status.Conditions = append(opiDPUSet.Status.Conditions, metav1.Condition{
		Type:               "DPFResourcesSynced",
		Status:             metav1.ConditionTrue,
		LastTransitionTime: metav1.Now(),
		Reason:             "SyncSuccessful",
		Message:            "All DPF resources are synced",
	})

	if err := r.Status().Update(ctx, opiDPUSet); err != nil {
		logger.Error(err, "Failed to update OPIDPUSet status")
		return ctrl.Result{}, err
	}

	// Requeue if not yet ready to keep polling DPF status.
	if opiDPUSet.Status.Phase != PhaseReady {
		logger.Info("DPUs not yet ready, requeuing", "phase", opiDPUSet.Status.Phase)
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
	}

	logger.Info("OPIDPUSet reconciliation complete", "phase", opiDPUSet.Status.Phase)
	return ctrl.Result{}, nil
}

// setErrorStatus is a helper to update the OPIDPUSet status on retryable error.
func (r *OPIDPUSetReconciler) setErrorStatus(ctx context.Context, obj *OPIDPUSet, reason, message string) {
	obj.Status.Phase = PhaseError
	obj.Status.Conditions = []metav1.Condition{
		{
			Type:               "DPFResourcesSynced",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: metav1.Now(),
			Reason:             reason,
			Message:            message,
		},
	}
	_ = r.Status().Update(ctx, obj)
}

// setTerminalError implements the Status-Commit-Before-TerminalError protocol.
// It commits the failure condition to etcd BEFORE signaling a terminal halt,
// preventing the controller manager from dropping state logs during immediate
// execution halt. This guarantees platform visibility for unrecoverable errors.
func (r *OPIDPUSetReconciler) setTerminalError(ctx context.Context, obj *OPIDPUSet, reason string, originalErr error) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	logger.Error(originalErr, "Unrecoverable error detected, committing status before terminal halt", "reason", reason)

	// Step 1: Commit status BEFORE signaling terminal halt.
	obj.Status.Phase = PhaseError
	obj.Status.Conditions = []metav1.Condition{
		{
			Type:               "HardwareValidationFailed",
			Status:             metav1.ConditionFalse,
			LastTransitionTime: metav1.Now(),
			Reason:             reason,
			Message:            originalErr.Error(),
		},
	}

	if statusErr := r.Status().Update(ctx, obj); statusErr != nil {
		// Status patch failed — return retryable error so we can try again.
		// Do NOT signal terminal halt if we failed to persist the reason.
		logger.Error(statusErr, "Failed to commit error status, will retry")
		return ctrl.Result{}, statusErr
	}

	// Step 2: Only after status is committed, signal terminal halt.
	return ctrl.Result{}, reconcile.TerminalError(originalErr)
}

// isUnrecoverableError determines whether an error represents an unrecoverable
// structural validation failure (e.g., immutable hardware config mismatch,
// secure-boot conflict, incompatible BFB image family). In a real implementation,
// this would inspect error types or codes from the DPF adapter.
func isUnrecoverableError(err error) bool {
	// Stub: in production, check for specific error types/codes:
	// - e.g. errors.As(err, &dpfv1.BFBIncompatibleError{})
	// - e.g. validating requested secure-boot config against physical node labels
	_ = err
	return false
}

// SetupWithManager registers the OPIDPUSetReconciler with the controller manager.
func (r *OPIDPUSetReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		// In a real implementation, .For() would reference the registered OPIDPUSet GVK.
		// We use a placeholder here since our types aren't registered with a real scheme.
		For(&OPIDPUSet{}).
		// Watches on owned DPF resources would be added here:
		// .Owns(&DPUSet{}).
		// .Owns(&BFB{}).
		Complete(r)
}

// OPIDPUServiceReconciler reconciles OPIDPUService objects by translating them
// into DPF DPUService CRDs and mapping status back.
type OPIDPUServiceReconciler struct {
	client.Client
	Scheme       *runtime.Scheme
	Adapter      DPFAdapter
	StatusMapper *StatusMapper
}

// Reconcile is the main reconciliation loop for OPIDPUService resources.
func (r *OPIDPUServiceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	logger.Info("Reconciling OPIDPUService", "name", req.NamespacedName)

	// 1. Fetch the OPIDPUService resource.
	opiSvc := &OPIDPUService{}
	if err := r.Get(ctx, req.NamespacedName, opiSvc); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	// 2. Vendor dispatch.
	if opiSvc.Spec.Vendor != "nvidia" {
		logger.Info("Skipping non-NVIDIA OPIDPUService", "vendor", opiSvc.Spec.Vendor)
		return ctrl.Result{}, nil
	}

	// 3. Handle deletion.
	if !opiSvc.DeletionTimestamp.IsZero() {
		if controllerutil.ContainsFinalizer(opiSvc, OPIFinalizer) {
			if err := r.Adapter.DeleteDPFResources(ctx, opiSvc); err != nil {
				return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
			}
			controllerutil.RemoveFinalizer(opiSvc, OPIFinalizer)
			if err := r.Update(ctx, opiSvc); err != nil {
				return ctrl.Result{}, err
			}
		}
		return ctrl.Result{}, nil
	}

	// 4. Ensure finalizer.
	if !controllerutil.ContainsFinalizer(opiSvc, OPIFinalizer) {
		controllerutil.AddFinalizer(opiSvc, OPIFinalizer)
		if err := r.Update(ctx, opiSvc); err != nil {
			return ctrl.Result{}, err
		}
	}

	// 5. Validate the target DPUSet exists and is ready.
	targetDPUSet := &OPIDPUSet{}
	targetKey := types.NamespacedName{
		Name:      opiSvc.Spec.TargetDPUSet,
		Namespace: opiSvc.Namespace,
	}
	if err := r.Get(ctx, targetKey, targetDPUSet); err != nil {
		logger.Error(err, "Target OPIDPUSet not found", "targetDPUSet", opiSvc.Spec.TargetDPUSet)
		opiSvc.Status.Phase = "Error"
		opiSvc.Status.Conditions = []metav1.Condition{
			{
				Type:               "TargetDPUSetReady",
				Status:             metav1.ConditionFalse,
				LastTransitionTime: metav1.Now(),
				Reason:             "TargetNotFound",
				Message:            fmt.Sprintf("OPIDPUSet %q not found", opiSvc.Spec.TargetDPUSet),
			},
		}
		_ = r.Status().Update(ctx, opiSvc)
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
	}

	if targetDPUSet.Status.Phase != "Ready" {
		logger.Info("Target DPUSet not ready, waiting", "phase", targetDPUSet.Status.Phase)
		opiSvc.Status.Phase = "Pending"
		opiSvc.Status.Conditions = []metav1.Condition{
			{
				Type:               "TargetDPUSetReady",
				Status:             metav1.ConditionFalse,
				LastTransitionTime: metav1.Now(),
				Reason:             "WaitingForDPUSet",
				Message:            fmt.Sprintf("Waiting for OPIDPUSet %q to become Ready (current: %s)", opiSvc.Spec.TargetDPUSet, targetDPUSet.Status.Phase),
			},
		}
		_ = r.Status().Update(ctx, opiSvc)
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
	}

	// 6. Ensure DPF DPUService.
	_, err := r.Adapter.EnsureDPUService(ctx, opiSvc)
	if err != nil {
		logger.Error(err, "Failed to ensure DPUService")
		opiSvc.Status.Phase = "Error"
		_ = r.Status().Update(ctx, opiSvc)
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}

	// 7. Sync status from DPF.
	dpfSvcName := opiSvc.Name + "-dpf"
	dpfSvcStatus, err := r.Adapter.GetDPUServiceStatus(ctx, dpfSvcName, DPFNamespace)
	if err != nil {
		logger.Error(err, "Failed to get DPUService status")
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, err
	}

	opiPhase, conditions := r.StatusMapper.MapDPUServicePhase(*dpfSvcStatus)
	opiSvc.Status.Phase = opiPhase
	opiSvc.Status.Conditions = conditions
	opiSvc.Status.VendorStatus = &NvidiaSvcVendorStatus{
		DPFDPUServiceName:  dpfSvcName,
		DPFDPUServicePhase: dpfSvcStatus.Phase,
	}

	// Add sync condition.
	opiSvc.Status.Conditions = append(opiSvc.Status.Conditions, metav1.Condition{
		Type:               "DPFServiceSynced",
		Status:             metav1.ConditionTrue,
		LastTransitionTime: metav1.Now(),
		Reason:             "SyncSuccessful",
		Message:            "DPF DPUService is synced",
	})

	if err := r.Status().Update(ctx, opiSvc); err != nil {
		logger.Error(err, "Failed to update OPIDPUService status")
		return ctrl.Result{}, err
	}

	if opiPhase != "Deployed" {
		return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
	}

	logger.Info("OPIDPUService reconciliation complete", "phase", opiPhase)
	return ctrl.Result{}, nil
}

// SetupWithManager registers the OPIDPUServiceReconciler with the controller manager.
func (r *OPIDPUServiceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&OPIDPUService{}).
		// .Owns(&DPUService{}).
		Complete(r)
}
